# Generated by Django 4.1.5 on 2024-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('grad_level', models.CharField(max_length=20)),
            ],
        ),
    ]
